In [4]:
#Installing relevant libraries
!pip install pandas
!pip install zipfile
!pip install kaggle

#import the pandas library
import pandas as pd

#import zipfile library (use this to extract file downloaded from kaggle)
import zipfile

#import kaggle library (use this to download the dataset programatically from Kaggle)
import kaggle

Requirement already satisfied: pandas in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement zipfile (from versions: none)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for zipfile

Requirement already satisfied: kaggle in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.2.1)
Requirement already satisfied: bleach in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.27 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (0.1.28)
Requirement already satisfied: packaging in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (7.35.0)
Requirement already satisfied: python-dateutil in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (4.68.1)
Requirement already satisfied: urllib3>=1.15.1 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (2.7.0)
Requirement already satisfied: webencodings in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from nbformat->jupytext->kaggle) (5.15.1)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: six>=1.5 in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\samir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: colorama in C:\Users\samir\AppData\Roaming\Python\Python314\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#pandas library for data manipulation and analysis
import pandas as pd

#load the london bike sharing dataset 
bikes = pd.read_csv("archive/london_merged.csv")

#display first 5 rows of dataset to check if data was loaded correctly
bikes.head()

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [5]:
#explore the data
bikes.info()

<class 'pandas.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  str
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), str(1)
memory usage: 1.3 MB

In [6]:
bikes.shape

(17414, 10)

In [7]:
bikes

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [8]:
#count the unique values in the weather_code column
bikes.weather_code.value_counts()

weather_code
1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: count, dtype: int64

In [9]:
#count the unique values in the season column
bikes.season.value_counts()

season
0.0    4394
1.0    4387
3.0    4330
2.0    4303
Name: count, dtype: int64

In [12]:
#specifying the column names that I want to use
new_cols_dict ={
    'timestamp' : 'time',
    'cnt' : 'count',
    't1' : 'temp_real_C',
    't2' : 'temp_feels_like_C',
    'hum' : 'humidity_percent',
    'wind_speed' : 'wind_speed_kph',
    'weather_code' : 'weather',
    'is_holiday' : 'is_holiday',
    'is_weekend' : 'is_weekend',
    'season' : 'season'

}

#renaming the columns to the specified column names
bikes.rename(new_cols_dict, axis=1, inplace=True)

In [13]:
#changing the humidity values to percentage
bikes.humidity_percent = bikes.humidity_percent / 100

In [14]:
#creating a season dictionary so that we can map the integers 0-3 to the actual written values
season_dict = {
    '0.0' : 'spring',
    '1.0' : 'summer',
    '2.0' : 'autumn',
    '3.0' : 'winter'
}

#creating a weather dictionary so that we can map the integers to the actual written values
weather_dict = {
    '1.0':'Clear',
    '2.0':'Scattered clouds',
    '3.0':'Broken clouds',
    '4.0':'Cloudy',
    '7.0':'Rain',
    '10.0':'Rain with thunderstorms',
    '26.0':'Snowfall'
}

#changing the seasons column data type to spring
bikes.season = bikes.season.astype('str')
#mapping the values 0-3 to the actual written seasons
bikes.season = bikes.season.map(season_dict)

#changing the weather column data type to string
bikes.weather = bikes.weather.astype('str')
#mapping the values to the actual written weathers
bikes.weather = bikes.weather.map(weather_dict)

In [ ]:
#checking dataframe to see if the mappings have worked
bikes.head()

,time,count,temp_real_C,temp_feels_like_C,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Broken clouds,0.0,1.0,winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clear,0.0,1.0,winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clear,0.0,1.0,winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clear,0.0,1.0,winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clear,0.0,1.0,winter

In [17]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
#writing the final dataframe to an excel file that we will use in our tableau visualitions. The will be the 'london_bikes_final.xlsx'
bikes.to_excel('london_bikes_final.xlsx', sheet_name='Data')